name: amqpop Release

on:
  release:

jobs:
  upload:
    name: Upload Release files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: build
        run: |
          version=`./scripts/dev/get-project-version.py`
          mvn clean install -DskipTests
          rm -rf pulsar-protocol-*
          cp amqp-impl/target/pulsar-protocol-handler-amqp-${version}.nar ./
          cp README.md ./pulsar-protocol-handler-amqp-readme.md
          echo "ls pulsar-protocol-*"
          ls pulsar-protocol-*

      - name: publish
        uses: skx/github-action-publish-binaries@release-0.11
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'pulsar-protocol-*'
